"""empty message

Revision ID: 12f95657229d
Revises: d0e54704f98d
Create Date: 2024-04-02 14:22:19.899705

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12f95657229d'
down_revision = 'd0e54704f98d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_table', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###
