// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBG4ks89wb9AkddMjsTUty_h0DU5dpR5cI',
    appId: '1:982651981367:web:9a8f92e5e3598762ba79b2',
    messagingSenderId: '982651981367',
    projectId: 'gettogether-9b658',
    authDomain: 'gettogether-9b658.firebaseapp.com',
    storageBucket: 'gettogether-9b658.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4Vllu_v1ZfVBwlctTkBI4ZL7Vhxafq3c',
    appId: '1:982651981367:android:936d7c8cc396f26bba79b2',
    messagingSenderId: '982651981367',
    projectId: 'gettogether-9b658',
    storageBucket: 'gettogether-9b658.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFC5kN8zBBrqngKYUBnY8N0-SkOxlOUvo',
    appId: '1:982651981367:ios:3cf5a5d286425f95ba79b2',
    messagingSenderId: '982651981367',
    projectId: 'gettogether-9b658',
    storageBucket: 'gettogether-9b658.appspot.com',
    iosBundleId: 'com.example.getTogether',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFC5kN8zBBrqngKYUBnY8N0-SkOxlOUvo',
    appId: '1:982651981367:ios:7b0ce69dfc2b841fba79b2',
    messagingSenderId: '982651981367',
    projectId: 'gettogether-9b658',
    storageBucket: 'gettogether-9b658.appspot.com',
    iosBundleId: 'com.example.getTogether.RunnerTests',
  );
}
